---
title: 'Collostructional analysis: A short primer'
author: "Stefan Hartmann"
date: "`r Sys.Date()`"
---


# What is collostructional analysis?

Collostructional anlysis is a family of methods measuring associations and dissociations between (usually) words and (synactic) constructions. Its theoretical background is Construction Grammar, a theory of language that assumes that language can be exhaustively described as an inventory of form-meaning pairs. These form-meaning pairs are called constructions and exist at various levels of abstraction. For collostructional analysis, so-called partially filled constructions are particularly relevant, i.e. patterns with a lexically fixed part and a variable slot. Classic examples include idiomatic patterns like [X *waiting to happen*] or [*The* X-*er the* Y-*er*], but the method can be applied to much more abstract constructions as well (e.g. imperatives, discussed in Stefanowitsch & Gries 2003).

Collostructional analysis comes in three major variants:

- Simple collexeme analysis. This variant checks which slot fillers occur at above-chance level in one open slot of a construction, compared to the frequency of the same slot fillers in all other constructions. It is therefore particularly well-suited for patterns with one open slot, e.g. [X waiting to happen].

- Distinctive collexeme analysis. This variant is used to compare two constructions by assessing which slot fillers occur with above-chance frequency in one construction compared to the other. Note that this variant only takes the frequencies of the slot fillers *within* the two constructions into account, i.e. the overall corpus frequencies are ignored.

- Covarying collexeme analysis. This variant assesses which slot fillers occur together with above-chance frequency in a construction with two open slots such as [*The* X-*er the* Y-*er*]. Again, only the frequency of the slot fillers  *within* the construction is taken into account, i.e. the overall corpus frequencies are ignored.

In Section \@ref{cba}, I will give a brief conceptual overview of the ideas behind collostructional analysis, its potential, and its limitations. The subsequent sections contain hands-on tutorials for each of the three variants of collostructional analysis, including extensions of distinctive collexeme analysis that allow for taking more than two constructions into account.

The subsequent sections discuss the three major variants of collostructional analysis using hands-on examples. The datasets used there can be downloaded from the "data" folder in this tutorial's [Github repository](https://github.com/empirical-linguistics/collostructions-tutorial/tree/main/data).


## What you will learn in this tutorial

In this tutorial, you will learn how to perform simple collostructional analyses using Flach's (2021) [`collostructions`](https://sfla.ch/collostructions/) package. I will also illustrate some basic data wrangling procedures (and some slightly more complex ones). 


## Prerequisites

If you already know some R, it will be easier for you to follow this tutorial, but if not, don't worry - you don't have to understand everything immediately, the main goal of this tutorial is to give an impression of the steps you'll have to take when doing collostructional analysis in R, without, however, discussing every single step in detail. 

In this tutorial, I will draw heavily on [`tidyverse`](https://www.tidyverse.org/) syntax. The Tidyverse is a family of packages implementing a couple of functions that make common data science tasks a bit easier. In order to follow this tutorial, you should therefore have the tidyverse packages installed (you cann install all of them via `install.packages("tidyverse")`).